[package]
name = "xivl-cli"
description = "The xivl command line over the 1.23b format libraries."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "xivl"
path = "src/main.rs"

[dependencies]
xivl-formats.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
jsonschema.workspace = true
same-file.workspace = true
csv.workspace = true
sha2.workspace = true

[lints]
workspace = true
