#!/usr/bin/env python3
"""Generator for the authored synthetic fixtures under tests/fixtures/public.

Every byte in that tree comes from this script. Nothing here is a copy, a
slice, a transformation, or a re-encoding of retail data: the layouts come
from the pages under docs/formats/ and the contents are deterministic patterns
this script invents.

    python tools/make_public_fixtures.py            # write the fixtures
    python tools/make_public_fixtures.py --check    # fail if any differ

The --check mode is the determinism proof, and CI runs it: a fixture that
cannot be regenerated byte-for-byte is a fixture nobody can audit.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from blowfish import Blowfish  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
PUBLIC_ROOT = REPO_ROOT / "tests" / "fixtures" / "public"

MAGIC = b"SEDB"
FIXED_HEADER_SIZE = 0x14
RES_EXTENDED_OFFSET = 0x30
RES_HEADER_SIZE = 0x40

BOM = b"\xef\xbb\xbf"
SCRAMBLE_MARKER = 0xFF
SCRAMBLE_KEY = 0x73
TOKEN_START = b"\x02"
TOKEN_END = b"\x03"

# Invented text. Nothing here is copied from a client string: the sheet
# fixtures need multi-byte UTF-8 to exercise the decoder, so they carry a
# two-, a three-, and a four-byte code point of this project's choosing.
MULTIBYTE = "row \u00e9 \u4e2d \U0002000b"


def pattern(length: int, seed: int) -> bytes:
    """A deterministic filler byte string that is obviously not real data."""
    return bytes(((index * 7 + seed) & 0xFF) for index in range(length))


def tag(text: str) -> bytes:
    value = text.encode("ascii")
    if len(value) > 4:
        raise ValueError("tag longer than four bytes: {0}".format(text))
    return value.ljust(4, b"\x00")


def sedb_header(
    subtype: str,
    unknown_a: int,
    flags: int,
    header_size: int,
    total_size: int,
    extended: bytes = b"",
) -> bytes:
    """The fixed SEDB header, zero padded out to header_size.

    `extended` is written at RES_EXTENDED_OFFSET when present.
    """
    header = bytearray(max(header_size, FIXED_HEADER_SIZE))
    header[0:4] = MAGIC
    header[4:8] = tag(subtype)
    struct.pack_into("<IHHI", header, 8, unknown_a, flags, header_size, total_size)
    if extended:
        header[RES_EXTENDED_OFFSET : RES_EXTENDED_OFFSET + len(extended)] = extended
    return bytes(header)


def res_extended(count: int, unknown_b: int, type_name: str, repeated: int | None = None) -> bytes:
    """The RES extended header block at 0x30: count, unknownB, count, tag."""
    if repeated is None:
        repeated = count
    return struct.pack("<III", count, unknown_b, repeated) + tag(type_name)


def directory_entry(index: int, offset: int, size: int, kind: int) -> bytes:
    return struct.pack("<IIII", index, offset, size, kind)


def utf16_field(text: str, width: int) -> bytes:
    """A UTF-16LE string in a fixed-width field, NUL terminated and zero
    padded, which is how the configuration files hold their text."""
    encoded = text.encode("utf-16-le") + b"\x00\x00"
    if len(encoded) > width:
        raise ValueError("text does not fit in {0} bytes: {1}".format(width, text))
    return encoded.ljust(width, b"\x00")


def staticactor_san(
    records: list[tuple[int, bytes]],
    *,
    declared_count: int | None = None,
) -> bytes:
    """An authored SAN record table using the retail framing only."""
    if declared_count is None:
        declared_count = len(records)
    decoded = bytearray(b"SYNTH")
    decoded.extend(struct.pack(">I", declared_count))
    for value, string in records:
        decoded.extend(struct.pack(">I", value))
        decoded.extend(string)
        decoded.append(0)
    return b"sane" + bytes(byte ^ 0x73 for byte in decoded)


def xml_document(body: str, declaration: bool = True, bom: bool = True) -> bytes:
    """An SSD document in the shape the client writes: BOM, declaration,
    CRLF line endings."""
    head = '<?xml version="1.0" encoding="utf-8"?>\n' if declaration else ""
    return (BOM if bom else b"") + (head + body).replace("\n", "\r\n").encode("utf-8")


# The scrambled-XML container. See docs/formats/ssd-sheet.md. The second word
# key is the encoder's free
# choice, so the fixtures use a value with bits in both halves: a zero key
# would let a broken key recovery still pass.
SCRAMBLE_TRAILER = 0xF1
KNOWN_PLAINTEXT_WORD = 0x6C6D
FIXTURE_WORD_KEY_B = 0xD2E8


def scramble_swap(buffer: bytearray) -> None:
    """The partial reversal, which is its own inverse."""
    low, high = 0, len(buffer) - 1
    while low < high:
        buffer[low], buffer[high] = buffer[high], buffer[low]
        low += 2
        high -= 2


def scramble_word_key(buffer: bytearray, start: int, key: int) -> None:
    for offset in range(start, len(buffer) - 1, 4):
        word = int.from_bytes(buffer[offset : offset + 2], "little") ^ key
        buffer[offset : offset + 2] = word.to_bytes(2, "little")


def scramble_document(document: bytes, key_b: int = FIXTURE_WORD_KEY_B) -> bytes:
    """Encode a document into the scrambled container."""
    encoded_length = len(document)
    buffer = bytearray(document)
    key_a = (encoded_length * 7) & 0xFFFF
    if encoded_length % 4 == 1:
        buffer[encoded_length - 1] ^= (key_a & 0xFF) ^ (key_b & 0xFF)
    scramble_word_key(buffer, 2, key_b)
    scramble_word_key(buffer, 0, key_a)
    scramble_swap(buffer)
    return bytes(buffer) + bytes([SCRAMBLE_TRAILER])


# The SQEX container. See docs/formats/sqex.md.
# The key is the fixture's own base name, so these fixtures are enciphered
# under the file name they are written to and renaming one makes it
# unreadable. The element and attribute names are invented: a synthetic
# vocabulary proves that the reader does not depend on retail names.
SQWT_SIGNATURE = b"SQEX" + bytes(4)


def widget_document(body: str, bom: bool = False) -> bytes:
    """A widget document in the shape the client writes: no declaration,
    CRLF line endings, and a byte order mark only where one is asked for."""
    return (BOM if bom else b"") + body.replace("\n", "\r\n").encode("utf-8")


def sqwt_container(relative: str, document: bytes) -> bytes:
    """Encipher a document under the base name of the path it is written
    to, which is the key the container uses."""
    name = Path(relative).name
    return SQWT_SIGNATURE + Blowfish(name.encode("utf-8")).encrypt(document)


def sheet_string(text: str, scrambled: bool = True) -> bytes:
    """One framed string value: u16 length, body, terminator.

    A scrambled body opens with 0xFF and the rest is XOR SCRAMBLE_KEY, so
    its NUL terminator reads as the key itself.
    """
    return framed_string(text.encode("utf-8"), scrambled)


def framed_string(payload: bytes, scrambled: bool = True) -> bytes:
    if scrambled:
        body = (
            bytes([SCRAMBLE_MARKER])
            + bytes(byte ^ SCRAMBLE_KEY for byte in payload)
            + bytes([SCRAMBLE_KEY])
        )
    else:
        body = payload + b"\x00"
    return struct.pack("<H", len(body)) + body


def token(code: int, payload: bytes, encoding: str = "direct") -> bytes:
    """One control token: 0x02 code length payload 0x03."""
    if encoding == "direct":
        length = bytes([len(payload) + 1])
    elif encoding == "byte":
        length = b"\xf0" + bytes([len(payload)])
    elif encoding == "byte-scaled":
        if len(payload) % 256:
            raise ValueError("the scaled length form carries whole multiples of 256")
        length = b"\xf1" + bytes([len(payload) // 256])
    elif encoding == "word":
        length = b"\xf2" + struct.pack(">H", len(payload))
    else:
        raise ValueError("unknown length encoding: {0}".format(encoding))
    return TOKEN_START + bytes([code]) + length + payload + TOKEN_END


def u32_array(values: list[int]) -> bytes:
    return b"".join(struct.pack("<I", value) for value in values)


def enable_records(pairs: list[tuple[int, int]]) -> bytes:
    return b"".join(struct.pack("<II", first, count) for first, count in pairs)


LUA51_HEADER = b"\x1bLuaQ\x00\x01\x04\x04\x04\x08\x00"
LUA51_MAXARG_SBX = (1 << 17) - 1


def lua_instruction_abc(opcode: int, a: int, b: int, c: int) -> int:
    return opcode | (a << 6) | (c << 14) | (b << 23)


def lua_instruction_abx(opcode: int, a: int, bx: int) -> int:
    return opcode | (a << 6) | (bx << 14)


def lua_instruction_asbx(opcode: int, a: int, sbx: int) -> int:
    return lua_instruction_abx(opcode, a, sbx + LUA51_MAXARG_SBX)


def lua_string(value: bytes | None) -> bytes:
    if value is None:
        return struct.pack("<I", 0)
    return struct.pack("<I", len(value) + 1) + value + b"\x00"


def lua_proto(
    *,
    source: bytes | None = None,
    lines: tuple[int, int] = (0, 0),
    shape: tuple[int, int, int, int] = (0, 0, 0, 2),
    instructions: tuple[int, ...] = (),
    constants: tuple[bytes, ...] = (),
    nested: tuple[bytes, ...] = (),
    line_info: tuple[int, ...] = (),
    locals_: tuple[tuple[bytes, int, int], ...] = (),
    upvalues: tuple[bytes, ...] = (),
) -> bytes:
    data = bytearray(lua_string(source))
    data.extend(struct.pack("<II4B", *lines, *shape))
    data.extend(struct.pack("<I", len(instructions)))
    for instruction in instructions:
        data.extend(struct.pack("<I", instruction))
    data.extend(struct.pack("<I", len(constants)))
    for constant in constants:
        data.extend(constant)
    data.extend(struct.pack("<I", len(nested)))
    for child in nested:
        data.extend(child)
    data.extend(struct.pack("<I", len(line_info)))
    for line in line_info:
        data.extend(struct.pack("<I", line))
    data.extend(struct.pack("<I", len(locals_)))
    for name, start_pc, end_pc in locals_:
        data.extend(lua_string(name))
        data.extend(struct.pack("<II", start_pc, end_pc))
    data.extend(struct.pack("<I", len(upvalues)))
    for name in upvalues:
        data.extend(lua_string(name))
    return bytes(data)


def build_fixtures() -> dict[str, bytes]:
    fixtures: dict[str, bytes] = {}

    # Authored Lua path and LPB samples contain no retail names or bytes.
    fixtures["lua-path/example.txt"] = b"Quest/Scenario/Man0g0.lua"
    fixtures["lua-path/non-ascii.bin"] = b"ab\xc3\xa9.lua"

    lua_chunk = b"\x1bLuaQ" + pattern(19, 0x31)
    fixtures["lpb/raw.bin"] = b"rlu\x0bABCD" + lua_chunk
    xor_header = b"rle\x0cWXYZ" + struct.pack("<I", 7) + b"!"
    fixtures["lpb/xor.bin"] = xor_header + bytes(byte ^ 0x73 for byte in lua_chunk)
    fixtures["lpb/truncated.bin"] = b"rle\x0cshort"
    fixtures["lpb/bad-chunk.bin"] = b"rlu\x0bABCDxxxxx"

    # -- GTEX and PWIB resources ----------------------------------------
    # The fields and boundaries are loader-evidenced; all values and source
    # bytes are invented.
    def gtex(
        data: bytes,
        *,
        format_index: int = 4,
        flags: int = 0,
        mip_levels: int = 1,
        width: int = 4,
        height: int = 4,
        depth: int = 1,
        data_base: int = 0x20,
        surfaces: tuple[tuple[int, int], ...] = (),
    ) -> bytes:
        header = bytearray(pattern(data_base, 0x31))
        header[0:4] = b"GTEX"
        header[6] = format_index
        header[7] = mip_levels
        header[9] = flags
        header[0x0A:0x10] = struct.pack(">HHH", width, height, depth)
        table_base = 0x18 if surfaces else 0
        header[0x10:0x14] = struct.pack(">I", table_base)
        header[0x14:0x18] = struct.pack(">I", data_base)
        for index, (offset, size) in enumerate(surfaces):
            entry = table_base + index * 8
            header[entry : entry + 8] = struct.pack(">II", offset, size)
        return bytes(header) + data

    fixtures["gtex/tagged.bin"] = gtex(
        pattern(40, 0x44), mip_levels=2, width=4, height=2,
        data_base=0x28, surfaces=((0, 32), (32, 8))
    )
    fixtures["gtex/trailing.bin"] = gtex(
        pattern(48, 0x51), format_index=24, mip_levels=2, width=8, height=8,
        data_base=0x28, surfaces=((0, 32), (40, 8))
    )
    fixtures["gtex/truncated-header.bin"] = b"GTEX" + pattern(10, 0x71)
    bad_gtex = bytearray(gtex(b"x"))
    bad_gtex[0x14:0x18] = struct.pack(">I", len(bad_gtex) + 1)
    fixtures["gtex/extent-out-of-range.bin"] = bytes(bad_gtex)

    def pwib(first: bytes, second: bytes, trailing: bytes = b"") -> bytes:
        first_offset = 0x10
        second_offset = first_offset + len(first)
        total_size = second_offset + len(second)
        header = b"PWIB" + struct.pack(">III", total_size, first_offset, second_offset)
        return header + first + second + trailing

    first = sedb_header("syn", 7, 2, 0x14, 37) + pattern(5, 0x62)
    fixtures["pwib/tagged.bin"] = pwib(first, pattern(12, 0x72))
    fixtures["pwib/trailing.bin"] = pwib(
        sedb_header("syn", 8, 2, 0x14, 29), pattern(9, 0x45), pattern(4, 0x55)
    )
    fixtures["pwib/truncated-header.bin"] = b"PWIB" + pattern(5, 0x55)
    fixtures["pwib/bad-nested-magic.bin"] = pwib(
        b"NOPE" + pattern(16, 0x75), pattern(4, 0x85)
    )
    bad_boundaries = bytearray(pwib(first, pattern(12, 0x72)))
    bad_boundaries[8:12] = struct.pack(">I", 0x30)
    fixtures["pwib/bad-boundaries.bin"] = bytes(bad_boundaries)
    fixtures["gtex/truncated-tag.bin"] = b"GTE"
    fixtures["pwib/truncated-tag.bin"] = b"PWI"

    # -- the static-actor SAN table --------------------------------------
    # Only the framing is promoted: the authored strings resemble paths so
    # the positive case exercises the retail byte class without assigning a
    # meaning to either record member.
    staticactor = staticactor_san(
        [(7, b"/Synthetic/One"), (0x10203040, b"/Synthetic/Two")]
    )
    fixtures["staticactor/records.bin"] = staticactor
    fixtures["staticactor/bad-magic.bin"] = b"x" + staticactor[1:]
    fixtures["staticactor/truncated-header.bin"] = staticactor[:12]
    fixtures["staticactor/count-bomb.bin"] = staticactor_san(
        [], declared_count=100_001
    )
    fixtures["staticactor/missing-record.bin"] = staticactor_san(
        [], declared_count=1
    )
    fixtures["staticactor/unterminated-record.bin"] = (
        staticactor_san([], declared_count=1)
        + bytes(byte ^ 0x73 for byte in struct.pack(">I", 9) + b"unfinished")
    )
    one_record = staticactor_san([(7, b"/Synthetic/One")])
    fixtures["staticactor/trailing-partial-record.bin"] = one_record + b"\x01\x02"
    fixtures["staticactor/trailing-record.bin"] = staticactor_san(
        [(7, b"/Synthetic/One"), (9, b"/Synthetic/Extra")], declared_count=1
    )

    child = lua_proto(
        lines=(4, 6),
        shape=(1, 1, 0, 2),
        instructions=(
            lua_instruction_asbx(22, 0, -1),  # JMP: iAsBx to this instruction
            lua_instruction_abc(30, 0, 1, 0),  # RETURN: iABC
        ),
        constants=(b"\x04" + lua_string(b"child"),),
        line_info=(5, 6),
    )
    main = lua_proto(
        source=b"@synthetic.lua",
        lines=(0, 12),
        shape=(1, 2, 2, 4),
        instructions=(
            lua_instruction_abc(0, 1, 2, 0),  # MOVE: iABC register and unused
            lua_instruction_abx(1, 0, 0),  # LOADK: iABx constant reference
            # ADD: the RK form keeps constant and register references distinct
            # without resolving either reference to a value.
            lua_instruction_abc(12, 2, 0x100 | 3, 1),
            lua_instruction_abx(36, 0, 0),  # CLOSURE: nested prototype 0
            lua_instruction_abc(4, 0, 0, 0),  # CLOSURE binding: parent upvalue 0
            lua_instruction_abc(34, 0, 0, 0),  # SETLIST: C is the following word
            1,  # SETLIST extra word, not an opcode
            lua_instruction_asbx(22, 0, -1),  # JMP: iAsBx and excess-K bias
            lua_instruction_abc(30, 0, 1, 0),  # RETURN: iABC
        ),
        constants=(
            b"\x00",
            b"\x01\x01",
            b"\x03" + struct.pack("<d", 1.5),
            b"\x04" + lua_string(b"hello"),
        ),
        nested=(child,),
        line_info=(1, 2, 3, 4, 4, 5, 5, 6, 7),
        locals_=((b"value", 0, 9),),
        upvalues=(b"environment",),
    )
    bytecode = LUA51_HEADER + main
    fixtures["lpb/bytecode.bin"] = b"rlu\x0bBCOD" + bytecode
    fixtures["lpb/bytecode-xor.bin"] = (
        b"rle\x0cBCOD" + struct.pack("<I", len(bytecode)) + b"?"
        + bytes(byte ^ 0x73 for byte in bytecode)
    )
    fixtures["lpb/bytecode-trailing.bin"] = b"rlu\x0bBCOD" + bytecode + b"!"
    unsupported = bytearray(bytecode)
    unsupported[6] = 2
    fixtures["lpb/bytecode-unsupported-header.bin"] = b"rlu\x0bBCOD" + unsupported
    invalid_opcode = lua_proto(instructions=(38,))
    fixtures["lpb/bytecode-invalid-opcode.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_opcode
    )
    invalid_constant = lua_proto(
        instructions=(
            lua_instruction_abx(1, 0, 1),
            lua_instruction_abc(30, 0, 1, 0),
        ),
        constants=(b"\x00",),
    )
    fixtures["lpb/bytecode-invalid-constant.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_constant
    )
    invalid_upvalue = lua_proto(
        instructions=(
            lua_instruction_abc(4, 0, 0, 0),
            lua_instruction_abc(30, 0, 1, 0),
        ),
    )
    fixtures["lpb/bytecode-invalid-upvalue.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_upvalue
    )
    invalid_nested = lua_proto(
        instructions=(
            lua_instruction_abx(36, 0, 0),
            lua_instruction_abc(30, 0, 1, 0),
        ),
    )
    fixtures["lpb/bytecode-invalid-nested.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_nested
    )
    invalid_register = lua_proto(
        instructions=(
            lua_instruction_abc(0, 2, 0, 0),
            lua_instruction_abc(30, 0, 1, 0),
        ),
    )
    fixtures["lpb/bytecode-invalid-register.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_register
    )
    invalid_jump = lua_proto(
        instructions=(
            lua_instruction_asbx(22, 0, -2),
            lua_instruction_abc(30, 0, 1, 0),
        ),
    )
    fixtures["lpb/bytecode-invalid-jump.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_jump
    )
    binding_child = lua_proto(
        shape=(1, 0, 0, 2),
        instructions=(lua_instruction_abc(30, 0, 1, 0),),
    )
    invalid_binding = lua_proto(
        shape=(1, 0, 0, 2),
        instructions=(
            lua_instruction_abx(36, 0, 0),
            lua_instruction_abx(1, 0, 0),
            lua_instruction_abc(30, 0, 1, 0),
        ),
        constants=(b"\x00",),
        nested=(binding_child,),
    )
    fixtures["lpb/bytecode-invalid-closure-binding.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_binding
    )
    invalid_setlist = lua_proto(
        instructions=(
            lua_instruction_abc(34, 0, 0, 0),
            lua_instruction_abc(30, 0, 1, 0),
        ),
    )
    fixtures["lpb/bytecode-invalid-setlist.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + invalid_setlist
    )
    truncated_instruction = (
        LUA51_HEADER
        + lua_string(None)
        + struct.pack("<II4BI", 0, 0, 0, 0, 0, 2, 2)
        + struct.pack("<I", lua_instruction_abx(1, 0, 0))
        + b"\x01\x00\x00"
    )
    fixtures["lpb/bytecode-instruction-truncated.bin"] = (
        b"rlu\x0bBCOD" + truncated_instruction
    )
    fixtures["lpb/bytecode-string-bomb.bin"] = (
        b"rlu\x0bBCOD" + LUA51_HEADER + struct.pack("<I", 16 * 1024 * 1024 + 1)
    )
    fixtures["lpb/bytecode-table-bomb.bin"] = (
        b"rlu\x0bBCOD"
        + LUA51_HEADER
        + lua_string(None)
        + struct.pack("<II4BI", 0, 0, 0, 0, 0, 2, 1_000_001)
    )
    deepest = lua_proto()
    for _ in range(128):
        deepest = lua_proto(nested=(deepest,))
    fixtures["lpb/bytecode-nesting-bomb.bin"] = b"rlu\x0bBCOD" + LUA51_HEADER + deepest

    # -- sedb ------------------------------------------------------------
    # A well-formed non-composite container: 0x30 header, 0x20 payload, and
    # a totalSize that covers the whole file as a top-level container does.
    plain_payload = pattern(0x20, 0x11)
    plain = sedb_header("txb", 1, 0x0200, 0x30, 0x50) + plain_payload
    fixtures["sedb/plain-container.bin"] = plain

    # The same container followed by eight unaccounted bytes. They must
    # survive into the report as trailing entries rather than vanish.
    fixtures["sedb/trailing-bytes.bin"] = plain + pattern(8, 0x40)

    # Ends mid-header: the flags field is not there. Expect
    # unexpected-end-of-input at offset 12.
    fixtures["sedb/truncated-header.bin"] = MAGIC + tag("txb") + struct.pack("<I", 1)

    # Wrong signature. Expect bad-magic at offset 0.
    fixtures["sedb/bad-magic.bin"] = b"SEDX" + tag("txb") + bytes(0x18)

    # headerSize below the fixed fields. Expect header-too-small at 0x0E.
    fixtures["sedb/header-too-small.bin"] = sedb_header("txb", 1, 0, 0x10, 0x20) + bytes(0x0C)

    # headerSize past the declared container. Expect
    # header-size-out-of-range at 0x0E.
    fixtures["sedb/header-size-out-of-range.bin"] = (
        sedb_header("txb", 1, 0, 0xFFFF, 0x20)[:0x20]
    )

    # The 0x10 field points past the end of the input. Expect
    # declared-size-out-of-range at 0x10.
    fixtures["sedb/declared-size-out-of-range.bin"] = sedb_header(
        "txb", 1, 0, 0x30, 0x1000
    ) + bytes(0x10)

    # The 0x10 field reads zero, below the container's own header. This is
    # the shape of the 145 retail mtb resources: not malformed, so the
    # parser falls back to the header extent, records the anomaly, and
    # reports the remainder as trailing bytes.
    fixtures["sedb/declared-size-below-header.bin"] = sedb_header("mtb", 0x43, 0, 0x40, 0) + pattern(
        0x20, 0x61
    )

    # -- res -------------------------------------------------------------
    # A composite container with two subresources, a nested SEDB child, and
    # a deliberate hole between the two extents.
    nested = sedb_header("shd", 0x1D, 0, 0x20, 0x30) + pattern(0x10, 0x21)
    assert len(nested) == 0x30
    gap = pattern(0x10, 0x31)
    tail = b"F00\\synthetic\\name-table".ljust(0x20, b"\x00")
    assert len(tail) == 0x20
    two = (
        sedb_header("RES ", 0xFA0, 0, RES_HEADER_SIZE, 0xC0, res_extended(2, 0x60, "brt"))
        + directory_entry(0, 0x00, 0x30, 2)
        + directory_entry(1, 0x40, 0x20, 0)
        + nested
        + gap
        + tail
    )
    assert len(two) == 0xC0
    fixtures["res/two-subresources.bin"] = two

    # One subresource whose declared extent runs 0x16 bytes past the end of
    # the file, the alignment slack the evidence document records. The
    # parser clamps it and reports the clamp. The case still succeeds.
    clamped = (
        sedb_header("RES ", 0xFA0, 0, RES_HEADER_SIZE, 0x6A, res_extended(1, 0x50, "brt"))
        + directory_entry(0, 0x00, 0x30, 4)
        + pattern(0x1A, 0x51)
    )
    assert len(clamped) == 0x6A
    fixtures["res/clamped-extent.bin"] = clamped

    # The two subresource counts disagree. Expect
    # subresource-count-mismatch at 0x38.
    fixtures["res/count-mismatch.bin"] = sedb_header(
        "RES ", 0xFA0, 0, RES_HEADER_SIZE, 0x60, res_extended(2, 0x60, "brt", repeated=3)
    ) + bytes(0x20)

    # A directory that cannot fit in the container. Expect
    # subresource-count-out-of-range at 0x30.
    fixtures["res/count-out-of-range.bin"] = sedb_header(
        "RES ", 0xFA0, 0, RES_HEADER_SIZE, 0x60, res_extended(0x1000, 0x60, "brt")
    ) + bytes(0x20)

    # A RES container with a 0x30 header, too small to hold the extended
    # fields. Expect header-too-small at 0x0E.
    fixtures["res/header-too-small.bin"] = sedb_header("RES ", 0xFA0, 0, 0x30, 0x60) + bytes(0x30)

    # -- resource-path ---------------------------------------------------
    fixtures["resource-path/ids.txt"] = (
        "# Resource identifiers for the resource-path conformance case.\n"
        "# Both text forms, both cases, and both ends of the 32-bit space.\n"
        "\n"
        "0x00000000\n"
        "0xFFFFFFFF\n"
        "0x29D90001\n"
        "89940554\n"
        "0x7eb50002\n"
        "0x000000FF\n"
        "0xFF000000\n"
    ).encode("ascii")

    # Seven hexadecimal digits. Expect invalid-resource-id at the offset of
    # the digits in the file.
    fixtures["resource-path/malformed-id.txt"] = (
        "# One identifier short of eight digits.\n0x29D9000\n"
    ).encode("ascii")

    # -- ssd documents ---------------------------------------------------
    # These carry a byte order mark, so they are byte fixtures rather than
    # text ones and take the .bin suffix the rest of the tree uses.

    # A master: sheets that are references to the documents defining them,
    # by decimal resource id.
    fixtures["ssd/master.bin"] = xml_document(
        '<ssd version="0.1">\n'
        '  <sheet name="synthetic/first" infofile="664076291" />\n'
        '  <sheet name="synthetic/second" infofile="45613057" />\n'
        "</ssd>\n"
    )

    # A schema document: two sheets, one language tagged, covering the five
    # base column types used by the compact fixture.
    fixtures["ssd/sheet-info.bin"] = xml_document(
        '<ssd version="0.1">\n'
        '  <sheet name="synthetic/first" mode="client" column_max="5" column_count="5"'
        ' cache="-1" type="none" lang="ja" infofile="">\n'
        "    <type>\n"
        "      <param>str</param>\n"
        "      <param>s32</param>\n"
        "      <param>bool</param>\n"
        "      <param>float</param>\n"
        "      <param>u8</param>\n"
        "    </type>\n"
        "    <index>\n"
        "      <param>0</param>\n"
        "      <param>3</param>\n"
        "    </index>\n"
        '    <block count="2">\n'
        '      <file begin="10000" count="7" offset="664076320" enable="664076319">664076318</file>\n'
        '      <file begin="30000" count="10" offset="664076393" enable="664076392">664076391</file>\n'
        "    </block>\n"
        "  </sheet>\n"
        '  <sheet name="synthetic/second" mode="client" column_max="1" column_count="1"'
        ' cache="0" type="all" infofile="">\n'
        "    <type><param>str</param></type>\n"
        "    <index><param>0</param></index>\n"
        '    <block count="1">\n'
        '      <file begin="0" count="3" offset="45613059" enable="45613058">45613057</file>\n'
        "    </block>\n"
        "  </sheet>\n"
        "</ssd>\n"
    )

    # An element that never closes. Expect malformed-xml.
    fixtures["ssd/unclosed-element.bin"] = xml_document(
        '<ssd version="0.1">\n  <sheet name="a" infofile="1">\n'
    )

    # A comment, and an entity reference. Both are outside the subset these
    # documents use, so both expect unsupported-xml-construct rather than a
    # reading this project has no evidence for.
    fixtures["ssd/comment.bin"] = xml_document(
        '<ssd version="0.1">\n  <!-- a note -->\n  <sheet name="a" infofile="1" />\n</ssd>\n'
    )
    fixtures["ssd/entity.bin"] = xml_document(
        '<ssd version="0.1">\n  <sheet name="a&amp;b" infofile="1" />\n</ssd>\n'
    )

    # A well-formed document that is not an ssd document. Expect
    # unexpected-element.
    fixtures["ssd/wrong-root.bin"] = xml_document(
        '<sdd version="0.1">\n  <sheet name="a" infofile="1" />\n</sdd>\n'
    )

    # A truncated multi-byte sequence in a name. Expect invalid-utf8.
    fixtures["ssd/not-utf8.bin"] = (
        BOM
        + b'<?xml version="1.0" encoding="utf-8"?>\r\n<ssd version="0.1">\r\n  <sheet name="'
        + b"\xc3\x28"
        + b'" infofile="1" />\r\n</ssd>\r\n'
    )

    # An infofile that is not a decimal id. Expect invalid-attribute-value.
    fixtures["ssd/bad-infofile.bin"] = xml_document(
        '<ssd version="0.1">\n  <sheet name="a" infofile="later" />\n</ssd>\n'
    )

    # -- enable files ----------------------------------------------------
    fixtures["sheet/enable-ranges.bin"] = enable_records(
        [(10000, 7), (11000, 39), (12000, 2)]
    )

    # Twelve bytes: one whole record and half of another. Expect
    # trailing-partial-record at offset 8.
    fixtures["sheet/enable-partial-record.bin"] = enable_records([(10000, 7)]) + struct.pack(
        "<I", 11000
    )

    # A range naming no rows, then one starting inside its predecessor.
    # Both are reported as anomalies. Neither stops the parse.
    fixtures["sheet/enable-anomalies.bin"] = enable_records([(20, 0), (10, 5), (12, 5)])

    # -- row-offset arrays -----------------------------------------------
    # Entry i is the end offset of row i, so a repeat is an empty slot.
    # Rows 0, 1, and 4 carry data. Rows 2 and 3 do not.
    fixtures["sheet/row-offsets.bin"] = u32_array([37, 74, 74, 74, 111])

    # Seven bytes. Expect trailing-partial-record at offset 4.
    fixtures["sheet/row-offsets-partial.bin"] = u32_array([37]) + b"\x00\x00\x00"

    # An entry that goes backwards, which cannot be an end offset. Expect a
    # row-offset-out-of-order anomaly and the entry preserved verbatim.
    fixtures["sheet/row-offsets-backward.bin"] = u32_array([40, 20, 60])

    # -- sheet strings ---------------------------------------------------
    scrambled_strings = (
        sheet_string("public fixture row one")
        + sheet_string(MULTIBYTE)
        + sheet_string("")
    )
    fixtures["sheet/strings-scrambled.bin"] = scrambled_strings
    fixtures["sheet/strings-plain.bin"] = (
        sheet_string("public fixture row one", scrambled=False)
        + sheet_string(MULTIBYTE, scrambled=False)
    )

    # A scrambled body whose last byte is not the key. Expect
    # malformed-sheet-string.
    broken = bytearray(sheet_string("public fixture row one"))
    broken[-1] = 0x41
    fixtures["sheet/string-bad-terminator.bin"] = bytes(broken)

    # A length prefix that runs past the end of the input. Expect
    # unexpected-end-of-input.
    fixtures["sheet/string-truncated.bin"] = struct.pack("<H", 0x40) + bytes(
        [SCRAMBLE_MARKER]
    ) + pattern(6, 0x13)

    # A truncated multi-byte sequence inside a decoded body. Expect
    # invalid-utf8.
    fixtures["sheet/string-not-utf8.bin"] = framed_string(b"ok\xc3\x28")

    # -- rich strings ----------------------------------------------------
    # Every length encoding, a payload that carries its own 0x02 .. 0x03
    # frame, and a token whose code this project does not interpret.
    rich = (
        "start".encode("utf-8")
        + token(0x10, b"")
        + "middle".encode("utf-8")
        + token(0x13, b"\xfe\xff\xf3\xf3\xf3")
        + token(0x09, b"payload", encoding="byte")
        + token(0x28, token(0x08, b"\x01"), encoding="direct")
        + token(0x1A, pattern(300, 0x07), encoding="word")
        + token(0x2C, pattern(256, 0x09), encoding="byte-scaled")
        + MULTIBYTE.encode("utf-8")
    )
    fixtures["sheet/rich-tokens.bin"] = framed_string(rich)

    # A token whose payload runs past the end of the string. Expect
    # malformed-rich-string-token.
    fixtures["sheet/rich-unterminated-token.bin"] = framed_string(
        b"start" + TOKEN_START + b"\x10\x40" + b"short"
    )

    # A length lead byte in the escape range that this project has not
    # established. Expect malformed-rich-string-token rather than a guess.
    fixtures["sheet/rich-unknown-length-lead.bin"] = framed_string(
        b"start" + TOKEN_START + b"\x10\xf3\x00\x00\x00" + TOKEN_END
    )

    # -- typed rows ------------------------------------------------------
    # Two rows of str,s32,bool,float,u8. A string column is
    # self-delimiting and the rest are fixed width, so the column list
    # alone fixes where a row ends.
    def typed_row(text: str, scrambled: bool, signed: int, flag: int, real: float, small: int) -> bytes:
        return (
            sheet_string(text, scrambled=scrambled)
            + struct.pack("<i", signed)
            + bytes([flag])
            + struct.pack("<f", real)
            + bytes([small])
        )

    first_row = typed_row("public fixture row one", True, -2, 1, 1.5, 9)
    second_row = typed_row(MULTIBYTE, False, 7, 0, 0.0, 255)
    fixtures["sheet/rows-typed.bin"] = first_row + second_row

    # The same shape with the final row cut short. Expect
    # unexpected-end-of-input rather than a silently dropped row.
    fixtures["sheet/rows-short.bin"] = first_row + second_row[:-3]

    # The five further column types the scrambled documents declare, whose
    # widths the row pass over the install established: one byte for s8,
    # two for s16, u16, and f16, four for u32.
    def widened_row(text: str, tiny: int, word: int, half: int, big: int) -> bytes:
        return (
            sheet_string(text, scrambled=False)
            + struct.pack("<b", tiny)
            + struct.pack("<h", word)
            + struct.pack("<H", half)
            + struct.pack("<I", big)
        )

    fixtures["sheet/rows-widened.bin"] = widened_row(
        "widened row one", -8, -300, 0x3C00, 4000000000
    ) + widened_row(MULTIBYTE, 127, 32767, 0xFFFF, 0)

    # -- the scrambled XML container -------------------------------------
    # Both document kinds, so a decoded document is proved to reach the
    # same reader a plaintext one reaches.
    fixtures["scrambled/master.bin"] = scramble_document(fixtures["ssd/master.bin"])

    scrambled_schema = xml_document(
        '<ssd version="0.1">\n'
        '\t<sheet name="synthetic/widened" mode="client" column_max="10" column_count="10"'
        ' cache="-1" type="none" lang="chs" infofile="">\n'
        "\t\t<type>\n"
        "\t\t\t<param>str</param>\n"
        "\t\t\t<param>u8</param>\n"
        "\t\t\t<param>s8</param>\n"
        "\t\t\t<param>bool</param>\n"
        "\t\t\t<param>u16</param>\n"
        "\t\t\t<param>s16</param>\n"
        "\t\t\t<param>f16</param>\n"
        "\t\t\t<param>u32</param>\n"
        "\t\t\t<param>s32</param>\n"
        "\t\t\t<param>float</param>\n"
        "\t\t</type>\n"
        "\t\t<index><param>0</param></index>\n"
        '\t\t<block count="1">\n'
        '\t\t\t<file begin="10000" count="2" offset="664076320" enable="664076319">664076318</file>\n'
        "\t\t</block>\n"
        "\t</sheet>\n"
        "</ssd>\n"
    )
    fixtures["scrambled/sheet-info.bin"] = scramble_document(scrambled_schema)

    # One fixture per encoded length modulo four. The final byte takes the
    # extra correction in exactly one of the four, so a decoder that gets
    # the rule wrong fails one of these and passes the rest.
    for residue in range(4):
        body = '<ssd version="0.1">{0}</ssd>\n'.format(" " * residue)
        document = xml_document(body)
        padding = (residue - len(document)) % 4
        document = xml_document(body.replace("</ssd>", " " * padding + "</ssd>"))
        assert len(document) % 4 == residue
        fixtures["scrambled/residue-{0}.bin".format(residue)] = scramble_document(document)

    # The trailer byte removed. Expect missing-scramble-trailer: without it
    # the client's own reader hands the file on untouched, so calling it a
    # document would be an invention.
    fixtures["scrambled/no-trailer.bin"] = fixtures["scrambled/master.bin"][:-1]

    # A trailer with too few bytes ahead of it to carry the second key.
    # Expect unexpected-end-of-input.
    fixtures["scrambled/short-body.bin"] = pattern(5, 0x11) + bytes([SCRAMBLE_TRAILER])

    # A file that ends in the trailer and is not a document. Expect
    # bad-magic: the trailer alone is not a signature.
    fixtures["scrambled/not-a-document.bin"] = pattern(48, 0x23) + bytes([SCRAMBLE_TRAILER])

    # A decode that opens correctly and then runs into a truncated
    # multi-byte sequence. Expect invalid-utf8.
    fixtures["scrambled/bad-utf8.bin"] = scramble_document(
        BOM
        + b'<?xml version="1.0" encoding="utf-8"?>\r\n<ssd version="0.1">\xc3\x28</ssd>\r\n'
    )

    # A decode that opens correctly and is not well formed. Expect
    # malformed-xml.
    fixtures["scrambled/malformed-xml.bin"] = scramble_document(
        xml_document('<ssd version="0.1">\n  <sheet name="unclosed">\n')
    )

    # -- the SQEX container ----------------------------------------------
    # A widget document with nesting, repeated element names, and a body
    # that does not divide evenly, so the final run stays in the clear.
    window = widget_document(
        '<SyntheticWindow Name="first" Width="320">\n'
        '\t<SyntheticPanel Name="body" Margin="4">\n'
        '\t\t<SyntheticLabel Name="title">public fixture</SyntheticLabel>\n'
        '\t\t<SyntheticLabel Name="detail" IsVisible="true" />\n'
        "\t</SyntheticPanel>\n"
        "</SyntheticWindow>\n"
    )
    fixtures["sqwt/window.bin"] = sqwt_container("sqwt/window.bin", window)

    # The two constructs the widget profile adds to the SSD subset, and
    # nothing else: a comment, and ampersand runs in text and in an
    # attribute value. Both are carried verbatim rather than expanded.
    dictionary = widget_document(
        '<SyntheticDictionary Version="1">\n'
        "\t<!-- an authored note, counted and not kept -->\n"
        '\t<SyntheticEntry Key="a" Label="one &amp; two">three &amp; four &</SyntheticEntry>\n'
        "</SyntheticDictionary>\n"
    )
    fixtures["sqwt/dictionary.bin"] = sqwt_container("sqwt/dictionary.bin", dictionary)

    # A body that divides evenly, so there is no plaintext tail at all. 155
    # retail containers take this shape and a reader that assumes a tail
    # would mishandle every one of them.
    aligned_body = '<SyntheticRoot Name="aligned">{0}</SyntheticRoot>\n'
    padding = -len(widget_document(aligned_body.format(""))) % 8
    fixtures["sqwt/aligned.bin"] = sqwt_container(
        "sqwt/aligned.bin", widget_document(aligned_body.format(" " * padding))
    )
    assert (len(fixtures["sqwt/aligned.bin"]) - 8) % 8 == 0

    # A document opening on a byte order mark, which 11 retail containers
    # do and the rest do not.
    fixtures["sqwt/byte-order-mark.bin"] = sqwt_container(
        "sqwt/byte-order-mark.bin",
        widget_document('<SyntheticRoot Name="marked" />\n', bom=True),
    )

    # A foreign signature. Expect bad-magic at offset 0.
    fixtures["sqwt/bad-magic.bin"] = b"GTEX" + bytes(4) + pattern(0x20, 0x71)

    # The tag with a reserved word that is not zero. Every one of the 1155
    # retail containers sets it to zero, so this is not one of them. Expect
    # bad-magic at offset 4.
    fixtures["sqwt/reserved-not-zero.bin"] = (
        b"SQEX" + struct.pack("<I", 1) + pattern(0x20, 0x73)
    )

    # Half a signature. Expect unexpected-end-of-input at offset 4.
    fixtures["sqwt/truncated-header.bin"] = b"SQEX"

    # A container enciphered under a name that is not the one it is stored
    # under, which is what reading a renamed file amounts to. The key is
    # wrong, so the body is not text: expect invalid-utf8.
    fixtures["sqwt/wrong-name.bin"] = SQWT_SIGNATURE + Blowfish(b"other.bin").encrypt(
        window
    )

    # A body that deciphers cleanly and is not a document. Expect
    # malformed-xml rather than a reading invented for it.
    fixtures["sqwt/not-a-document.bin"] = sqwt_container(
        "sqwt/not-a-document.bin", b"plain text, no element anywhere in it\r\n"
    )

    # A CDATA section: inside the widget profile's reach and outside its
    # grammar, so the profile stays bounded. Expect
    # unsupported-xml-construct.
    fixtures["sqwt/cdata.bin"] = sqwt_container(
        "sqwt/cdata.bin",
        widget_document("<SyntheticRoot><![CDATA[x]]></SyntheticRoot>\n"),
    )

    # A comment that never closes. Expect malformed-xml.
    fixtures["sqwt/unclosed-comment.bin"] = sqwt_container(
        "sqwt/unclosed-comment.bin",
        widget_document("<SyntheticRoot>\n\t<!-- never closed\n</SyntheticRoot>\n"),
    )

    # -- the configuration files -----------------------------------------
    # The shapes come from docs/formats/configuration.md; every value is this
    # project's own. The stamps are authored
    # date-shaped words rather than the client's two constants, because the
    # reader does not test the stamp and a fixture should not read as a
    # copy of one.
    fixtures["config/sys-grid.bin"] = (
        struct.pack("<I", 0x20260801)
        + struct.pack("<III", 1, 0, 0x02D0)
        + utf16_field("Synthetic Font", 32)
        + utf16_field("synthetic\\path", 32)
        + b"TAGS"
        + struct.pack("<III", 0, 0xDEADBEEF, 0)
    )
    assert len(fixtures["config/sys-grid.bin"]) % 4 == 0

    # The pad shape: a stamp, a sixteen-byte device identifier, a count, and
    # a byte mapping. Both of the census's false positives are here on
    # purpose - the identifier reads as eight printable UTF-16 units and the
    # mapping as twelve printable bytes, and neither is text.
    fixtures["config/pad-grid.bin"] = (
        struct.pack("<I", 0x20260802)
        + b"\xa1\x41\xa2\x42\xa3\x43\xa4\x44\xa5\x45\xa6\x46"
        + b"TEST"
        + struct.pack("<I", 2)
        + bytes(range(0x30, 0x3C))
        + bytes(4 * 9)
    )
    assert len(fixtures["config/pad-grid.bin"]) % 4 == 0

    # Two words and no stamp, which is the whole of the language file.
    fixtures["config/lng-words.bin"] = struct.pack("<II", 0, 2)

    # A grid with no words at all. The stamped files refuse this and the
    # unstamped ones do not, which is the difference between them.
    fixtures["config/lng-empty.bin"] = b""

    # The region file is not a grid: its bytes are carried whole, so the
    # fixture uses a length no word boundary allows and content that is not
    # zero, which the retail file's five zero bytes would not exercise.
    fixtures["config/rgn-body.bin"] = bytes([1, 2, 3, 4, 5])

    # A grid ending in a run shorter than a word. Nothing states a length
    # and nothing terminates it, so the leftover is unaccountable. Expect
    # trailing-partial-record at the offset the leftover starts.
    fixtures["config/sys-partial-word.bin"] = struct.pack("<II", 0x20260801, 7) + b"\x01\x02"
    fixtures["config/lng-partial-word.bin"] = struct.pack("<I", 3) + b"\x09"

    # Less than the leading stamp. Expect unexpected-end-of-input.
    fixtures["config/sys-short-stamp.bin"] = b"\x01\x02\x03"
    fixtures["config/pad-short-stamp.bin"] = b"\x01\x02"

    return fixtures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed fixtures match this generator and exit non-zero if not",
    )
    args = parser.parse_args()

    fixtures = build_fixtures()
    differences = []
    for relative, data in sorted(fixtures.items()):
        path = PUBLIC_ROOT / relative
        if args.check:
            if not path.exists():
                differences.append("{0}: missing".format(relative))
            elif path.read_bytes() != data:
                differences.append("{0}: differs from the generator".format(relative))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

    actual = {
        path.relative_to(PUBLIC_ROOT).as_posix()
        for path in PUBLIC_ROOT.rglob("*")
        if path.is_file() and path.relative_to(PUBLIC_ROOT).as_posix() != "README.md"
    }
    for relative in sorted(actual - fixtures.keys()):
        differences.append("{0}: not produced by the generator".format(relative))

    if differences:
        for line in differences:
            print("fixtures: {0}".format(line))
        print("fixtures: FAILED ({0} finding(s))".format(len(differences)))
        return 1

    if args.check:
        print("fixtures: OK ({0} fixture(s) reproduce)".format(len(fixtures)))
        return 0

    print("fixtures: wrote {0} fixture(s)".format(len(fixtures)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
